[workspace]
resolver = "2"
members = ["lib", "nannou_dynamic"]

[package]
name = "{{project-name}}"
authors = ["{{authors}}"]
version = "0.1.0"
edition = "2021"

[dependencies]
hot-lib-reloader = { version = "^0.6", optional = true }
lib = { path = "./lib" }
nannou = { package = "nannou_dynamic", path = "./nannou_dynamic" }

[features]
default = []
reload = ["dep:hot-lib-reloader"]
